spring:
  application:
    name: auth-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8191

token:
  ttl: 3600000
  secret: "https://www.youtube.com/watch?v=VBUMYOYJISc"

vars:
  task-management-service-url: ${TASK_MANAGEMENT_SERVICE_URL}
